services:

  manager:
    build:
      context: .
      dockerfile: Manager/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - worker1
      - worker2
      - worker3
      - worker4
    networks:
      - crackhash-network

  worker1:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    networks:
      - crackhash-network

  worker2:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    networks:
      - crackhash-network

  worker3:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    networks:
      - crackhash-network

  worker4:
    build:
      context: .
      dockerfile: Worker/Dockerfile
    networks:
      - crackhash-network
    
  mongo1:
    image: mongo:7
    container_name: mongo1
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db
    networks:
      - crackhash-network

  mongo2:
    image: mongo:7
    container_name: mongo2
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db
    networks:
      - crackhash-network

  mongo3:
    image: mongo:7
    container_name: mongo3
    command: [ "mongod", "--replSet", "rs0", "--bind_ip_all" ]
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db
    networks:
      - crackhash-network
    
  mongo-setup:
    image: mongo:7
    container_name: mongo-setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./mongo-init:/scripts
    entrypoint: [ "bash", "-c", "sleep 8 && mongosh mongodb://mongo1:27017 /scripts/init-replica.js" ]
    networks:
      - crackhash-network
    restart: "no"

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:

networks:
  crackhash-network:
    driver: bridge